### ISSUE TITLE
InputMemoryBitStream::CopyConstructor: Incorrect byteCount

### ISSUE THREAD

**Issue by mwistauder** [MultiplayerBook/MultiplayerBook#11]
Hello!

When you calculate byteCount by dividing mBitCapacity by 8, you lose 1 byte.

```
InputMemoryBitStream( const InputMemoryBitStream& inOther ) :
	mBitCapacity( inOther.mBitCapacity ),
	mBitHead( inOther.mBitHead ),
	mIsBufferOwner( true )
	{
		//allocate buffer of right size
		int byteCount = mBitCapacity / 8;
		mBuffer = static_cast< char* >( malloc( byteCount ) );
		//copy
		memcpy( mBuffer, inOther.mBuffer, byteCount );
	}
```

[Link to the line in your repo](https://github.com/MultiplayerBook/MultiplayerBook/blob/master/Chapter%2012/RoboCatRTS/RoboCatRTS/Inc/MemoryBitStream.h#L100)

A solution would be adding the following code after `int byteCount = ...`
```
if (mBitCapacity % 8 != 0)
		byteCount++;
```
Best Regards

**Comment by JoshuaGlazer** [comment]
Thanks! That's a good point we didn't run into in testing. Another solution is to just do 

byteCount = (mBitCapacity + 7) / 8;
That will make sure that if there's at least one extra bit you get a whole extra byte. I'll look into updating the repo. 
Thanks very much again!
Josh

**Comment by mwistauder** [comment]
Yes, that's a better solution, thanks!
