### ISSUE TITLE
Education Material

### ISSUE THREAD

**Issue by FabioAnthony** [MultiplayerBook/MultiplayerBook#18]
Hey MGP Team and @JoshuaGlazer,

in the book it mentions that there would be "links **PowerPoints slides** and a **sample syllabus** for use in an academic setting" on this companion site.
What I (externally) found was : [https://web-app.usc.edu/ws/soc_archive/soc/syllabus/20133/31898.pdf]

Somehow, I did manage to find any academic material here, is it still available (if yes, could you, please, provide the direct link for this lost soul :D )?

In any event, thank you for the great book!
Fabio

**Comment by chalonverse** [comment]
The slides are available on the Pearson Higher Ed site here: https://www.pearson.com/us/higher-education/program/Glazer-Multiplayer-Game-Programming-Architecting-Networked-Games/PGM317032.html?tab=resources

**Comment by FabioAnthony** [comment]
Hi Sanjay,

thank very much for the reply.
I registered at Pearson.com and am now awaiting approval.

All the best,
Fabio

Von: chalonverse [mailto:notifications@github.com]
Gesendet: 18 January 2021 22:13
An: MultiplayerBook/MultiplayerBook <MultiplayerBook@noreply.github.com>
Cc: Anthony, Fabio <fabio.anthony@th-luebeck.de>; Author <author@noreply.github.com>
Betreff: Re: [MultiplayerBook/MultiplayerBook] Education Material (#18)


The slides are available on the Pearson Higher Ed site here: https://www.pearson.com/us/higher-education/program/Glazer-Multiplayer-Game-Programming-Architecting-Networked-Games/PGM317032.html?tab=resources
