### ISSUE TITLE
Missing Assets

### ISSUE THREAD

**Issue by aceiii** [MultiplayerBook/MultiplayerBook#2]
I'm trying to build the code on OSX 10.11 with XCode 7.2 and it's complaining of missing Assets directory.
```
The working directory "$(SRCROOT)/Assets" for scheme "Chapter3" doesn't exist.
```

It also says the build is successful, but there are 2 errors related to a bash script that is being run:

```
cp: Assets: No such file or directory
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure
```

Thanks.

**Comment by JoshuaGlazer** [comment]
Hi aceiii-

Thanks for writing!

Chapter 3 doesn't have an executable example, just sample wrappers for socket data structures and functions. So you've definitely found a bug in the project file, but once I've fixed it, it won't actually produce anything runnable. The later chapters ( starting at 6 I believe ) have actual executables that will run ( and build properly as well...).

Thanks again for the note!

Josh

**Comment by aceiii** [comment]
Okay I see now, thanks for the clarification!
