### ISSUE TITLE
SocketUtil::Select error?

### ISSUE THREAD

**Issue by aceiii** [MultiplayerBook/MultiplayerBook#3]
Just reading through the book and noticed what seemed like an error:

```
	fd_set *readPtr = FillSetFromVector( read, inReadSet, nfds );
	fd_set *writePtr = FillSetFromVector( read, inWriteSet, nfds );
	fd_set *exceptPtr = FillSetFromVector( read, inExceptSet, nfds );
```

Should those 3 `read`s instead be `read`,`write`, and `except`?

**Comment by JoshuaGlazer** [comment]
Thanks! Good catch- sorry about that! Too much copy pasta.  I pushed a fix to the repo for both this and the Assets issue.
Cheers!
Josh
