### ISSUE TITLE
PowerPoint slides and sample syllabus?

### ISSUE THREAD

**Issue by ptychan** [MultiplayerBook/MultiplayerBook#6]
Hello, just wondering where I can access the PowerPoint slides and sample syllabus please? Thanks.

**Comment by chalonverse** [comment]
https://www.pearsonhighered.com/program/Glazer-Multiplayer-Game-Programming-Architecting-Networked-Games/PGM317032.html

**Comment by carlosdanna** [comment]
Hello @chalonverse , I don't have access to download those resources is there a way to do this without sign in?

**Comment by chalonverse** [comment]
Unfortunately, the slide access is limited to only registered instructors through Pearson (this is how the publisher handles it). Are you not able to sign up/request access?

**Comment by DoctorMikeReddy** [comment]
I have registered and asked for verification, and it has been ignored for weeks :-(
